### ISSUE TITLE
Setup CI to run checks and tests

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/contract-library#3]
Run the written tests for all contracts. 
Run solium on own contracts. We decided we dont want to do cosmetic improvements of contracts not written by ourselves.

**Comment by schmir** [comment]
initial configuration is in the https://github.com/trustlines-network/contract-library/tree/feature/cci-intial-config branch.

The problem is that solium complains about errors, we have trailing whitespace and it's unclear if we want to change that. We could also turn off solium, but then the circleci workflow is empty.

If we want to track changes from upstream, we should only make changes to the source code here if necessary, e.g. cosmetic changes should not be done. 

also see #4
